import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import Navbar from "@/components/Navbar/Navbar";
import StoreProvider from "./StoreProvider";
import { SearchProvider } from "@/context/SearchContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <SearchProvider>
            <Navbar />
            {children}
          </SearchProvider>
        </StoreProvider>
      </body>
    </html>
  );
}

